manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/MangoIV
  projects:
    - name: zmk
      remote: zmk
      revision: draculady
      import: app/west.yml
  self:
    path: config
